conf: annotate meta-rdk base64 mask
I accidentally disabled this while verifying the webconfig-framework
change.
We should make sure it does not accidentally get removed in the
future.

ExpansionError during parsing meta-rdk/recipes-support/base64/base64_git.bb
bb.data_smart.ExpansionError: Failure expanding variable SRCPV
fatal: could not read Username for 'https://gerrit.teamccp.com': No such device or addres
The variable dependency chain for the failure is: SRCPV -> AUTOREV[vardepvalue]