start-parodus: use PLATFORM_GENERICARM define to start-parodus.c
While evaluating the WebPA changes, I encountered this error:

From parodusStart/start_parodus.c:47:
parodusStart/start_parodus.c: In function 'main':
parodusStart/start_parodus.c:328:59: error:
'CONFIG_VENDOR_NAME' undeclared (first use in this function)
  328 |         rc = strcpy_s(manufacturer, sizeof(manufacturer), CONFIG_VENDOR_NAME);
      |                                                           ^~~~~~~~~~~~~~~~~~

The issue is caused by ccsp_vendor.h not being imported on our platform.
Add a bbappend to put this into effect

Signed-off-by: Mathew McBride <matt@traverse.com.au>