rdk-wifi-hal: fix 2025.Q4 specific compile issues
src/wifi_hal_nl80211_events.c:132:1: error: control reaches
	end of non-void function [-Werror=return-type]
src/wifi_hal_nl80211_events.c:61:9: error: unused variable
	'phy_rate' [-Werror=unused-variable]