ccsp-one-wifi-libwebconfig: fix compile error with missing run_qmgr.h
RDKB-66764/65/66 introduced WiFi Experience related features
in OneWifi.

See https://code.rdkcentral.com/r/c/rdk/components/generic/rdk-oe/meta-rdk-broadband/+/129476
and/or
git -C meta-rdk-broadband diff 1ae19678d66f6b787928f1eeccf05823f3468 6d00a1a76e870e02fbda541cabf7c9e9b3636

Our older, pinned SRCREV does not install the header file
`run_qmgr.h`, so override the variable that controls it's
installation.

Fixes this compile error that appeared in the 2026-10-07 daily build:
| install: cannot stat 'build/build-armefi64-rdk-broadband/tmp/work/cortexa53-rdk-linux/
	ccsp-one-wifi-libwebconfig/6.1+gitAUTOINC+d17bd2d25f-r0/git/include/run_qmgr.h': No such file or directory

NOTE: recipe ccsp-one-wifi-libwebconfig-6.1+gitAUTOINC+d17bd2d25f-r0: task do_install: Failed
ERROR: Task (mc:generic:meta-rdk-broadband/recipes-ccsp/ccsp/ccsp-one-wifi-libwebconfig.bb:do_install) failed
	with exit code '1'